var cpuPrev="0,0";function esc(t){return t?String(t).replace(/[&<>'"]/g,(function(t){return{"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[t]})):""}function loadSystemInfo(){var t=L.rpc.declare({object:"system",method:"board"
}),e=L.rpc.declare({object:"system",method:"info"});Promise.all([t(),e()]).then((function(t){var e=t[0]||{},r=t[1]||{},a=document.getElementById("model-value");a&&e.model&&(a.textContent=e.model)
;var i=document.getElementById("firmware-value");i&&e.release&&e.release.description&&(i.textContent=e.release.description);var d=document.getElementById("uptime-value");d&&r.uptime&&(window._uptimeStart=r.uptime,
window._uptimeLoadedAt=Date.now(),d.textContent=formatUptime(r.uptime),startUptimeTicker())}))}function formatUptime(t){return Math.floor(t/3600)+"h "+Math.floor(t%3600/60)+"m "+Math.floor(t%60)+"s"}function startUptimeTicker(){
if(window._uptimeStart&&void 0!==window._uptimeLoadedAt){var t=document.getElementById("uptime-value");t&&(e(),setInterval(e,1e3))}function e(){var e=(Date.now()-window._uptimeLoadedAt)/1e3,r=window._uptimeStart+e
;t.textContent=formatUptime(r)}}function renderCPUWidget(t){
var e=Number(t.usage)||0,r=esc(t.loadavg||"0.00 0.00 0.00"),a=esc(null!=t.cores?t.cores:"?"),i=e<50?"linear-gradient(90deg, #4CAF50, #8BC34A)":e<80?"linear-gradient(90deg, #FF9800, #FFC107)":"linear-gradient(90deg, #F44336, #FF5722)"
;document.getElementById("cpu-widget").innerHTML='<table class="table"><tr class="tr"><td class="td left" width="33%">CPU Usage</td><td class="td left"><div class="cbi-progressbar cpu-bar" title="'+e+'%"><div style="width:'+e+"%; background: "+i+';">'+e+'%</div></div></td></tr><tr class="tr"><td class="td left" width="33%">Cores</td><td class="td left">'+a+'</td></tr><tr class="tr"><td class="td left" width="33%">Load Average</td><td class="td left">'+r+"</td></tr></table>"
}function renderMemoryWidget(t){var e=t.total||0,r=t.free||0,a=t.buffered||0,i=t.cached||0,d=t.available||r+a,o=e-r,n=e>0?Math.floor(o/e*100):0,s='<table class="table">'
;s+='<tr class="tr"><td class="td left" width="33%">Total Available</td><td class="td left">'+formatBytes(d)+" / "+formatBytes(e)+"</td></tr>",
s+='<tr class="tr"><td class="td left" width="33%">Used</td><td class="td left"><div class="cbi-progressbar" title="'+n+'%"><div style="width:'+n+'%; background: linear-gradient(90deg, #4CAF50, #8BC34A);">'+n+"%</div></div>"+formatBytes(o)+" / "+formatBytes(e)+"</td></tr>",
a>0&&(s+='<tr class="tr"><td class="td left" width="33%">Buffered</td><td class="td left">'+formatBytes(a)+"</td></tr>"),i>0&&(s+='<tr class="tr"><td class="td left" width="33%">Cached</td><td class="td left">'+formatBytes(i)+"</td></tr>"),
s+="</table>",document.getElementById("memory-widget").innerHTML=s}function renderStorageWidget(t){var e='<table class="table">';if(t.root){var r=t.root.used||0,a=t.root.total||0,i=a>0?Math.floor(r/a*100):0
;e+='<tr class="tr"><td class="td left" width="33%">Disk space</td><td class="td left"><div class="cbi-progressbar" title="'+i+'%"><div style="width:'+i+'%; background: linear-gradient(90deg, #FF9800, #FFC107);">'+i+"%</div></div><small>"+formatBytes(r)+" / "+formatBytes(a)+"</small></td></tr>"
}if(t.tmp){var d=t.tmp.used||0,o=t.tmp.total||0,n=o>0?Math.floor(d/o*100):0
;e+='<tr class="tr"><td class="td left" width="33%">Temp space</td><td class="td left"><div class="cbi-progressbar" title="'+n+'%"><div style="width:'+n+'%; background: linear-gradient(90deg, #2196F3, #64B5F6);">'+n+"%</div></div><small>"+formatBytes(d)+" / "+formatBytes(o)+"</small></td></tr>"
}e+="</table>",document.getElementById("storage-widget").innerHTML=e}function mergeTrafficData(t,e){return t.map((function(t){var r=e[t.name];return t.rx_bytes=r&&r.rx_bytes||0,t.tx_bytes=r&&r.tx_bytes||0,t}))}
function renderNetworkWidget(t){var e="",r=t.filter((function(t){return!t.name.match(/^[25]\.?4?GHz$/i)&&!t.name.match(/^wlan/)&&!t.name.match(/^phy/)}));r.length>0?(e+='<div style="display: flex; flex-wrap: wrap; gap: 12px;">',
r.forEach((function(t){
var r=t.carrier,a=t.speed&&t.speed>0?t.speed:null,i=r?"rgba(76, 175, 80, 0.12)":"rgba(255, 255, 255, 0.03)",d=r?"rgba(76, 175, 80, 0.5)":"rgba(255, 255, 255, 0.08)",o=r?"#4CAF50":"#888",n=r?"●":"○",s=t.name.match(/wan/i)?"WAN":"LAN",l=""
;r&&a&&(l=a>=1e3?(a/1e3).toFixed(1)+" Gbps":a+" Mbps"),e+='<div style="background: '+i+"; border: 1px solid "+d+'; border-radius: 12px; padding: 16px; text-align: center; min-width: 100px; flex: 1;">',
e+='<div style="font-size: 10px; text-transform: uppercase; color: #999; letter-spacing: 0.5px; margin-bottom: 6px;">'+s+"</div>",e+='<div style="font-size: 16px; color: #fff; font-weight: 700; margin-bottom: 6px;">'+esc(t.name)+"</div>",
e+='<div style="font-size: 12px; color: '+o+'; font-weight: 500;">'+n+" "+(r?"Connected":"No Link")+"</div>",l&&(e+='<div style="font-size: 11px; color: #aaa; margin-top: 4px;">'+l+"</div>"),e+="</div>"})),
e+="</div>"):e='<div style="color:#999;">No Ethernet ports found</div>',document.getElementById("network-widget").innerHTML=e}function renderWirelessWidget(t){var e=""
;0!==t.length?(e+='<div style="display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 20px;">',t.forEach((function(t){var r=t.carrier,a=r?"#42A5F5":"#888",i=r?"Active":"Down",d=r?"●":"○"
;e+='<div style="background: '+(r?"rgba(33, 150, 243, 0.12)":"rgba(255, 255, 255, 0.03)")+"; border: 1px solid "+(r?"rgba(33, 150, 243, 0.5)":"rgba(255, 255, 255, 0.08)")+'; border-radius: 10px; line-height:1.5; padding: 14px 18px; text-align: center; min-width: 120px; flex: 1;">',
e+='<div style="font-size: 16px; text-transform: uppercase; color: #999; letter-spacing: 0.5px; margin-bottom: 6px;">WiFi</div>',e+='<div style="font-size: 25px; color: #fff; font-weight: 700; margin-bottom: 6px;">'+esc(t.iface)+"</div>",
e+='<div style="font-size: 17px; color: '+a+'; font-weight: 500;">'+d+" "+i+"</div>",e+="</div>"})),e+="</div>",t.forEach((function(t){
var r=Array.isArray(t.clients)?t.clients:t.clients&&"object"==typeof t.clients?Object.values(t.clients):[];if(r&&0!==r.length){var a=t.iface.replace("GHz"," GHz"),i=t.iface.startsWith("2.4")?"#edf0f1":"#C62828"
;e+='<div style="background:#24313e; border-radius: 12px; padding: 16px; margin-bottom: 16px;">',e+='<div style="display: flex; align-items: center; gap: 12px; margin-bottom: 12px;">',
e+='<span style="background: #1f7fd1; color: #fff; padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: 700;">'+esc(t.ssid||t.iface)+"</span>",
e+='<span style="background: '+i+"; color: "+(t.iface.startsWith("2.4")?"#000":"#fff")+'; padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: 700; margin-right: 4px;">'+esc(a)+"</span>",
e+='<span style="color: #aaa; font-size: 11px;">👥 '+r.length+" clients</span>",e+="</div>",e+='<div style="overflow-x: auto;text-align:left;"><table class="table">',
e+='<tr class="tr" style="border-bottom: 1px solid rgba(255,255,255,0.1);">',e+='<th style="color:#999; font-size:14px; padding:6px;">Hostname</th>',e+='<th style="color:#999; font-size:14px; padding:6px;">IP Address</th>',
e+='<th style="color:#999; font-size:14px; padding:6px;">MAC</th>',e+='<th style="color:#999; font-size:14px; padding:6px;">Signal</th>',e+="</tr>",r.forEach((function(t){var r=t.signal>-50?"#4CAF50":t.signal>-70?"#FF9800":"#F44336"
;e+='<tr class="tr" style="border-bottom: 1px solid rgba(255,255,255,0.03);">',e+='<td style="color:#fff; font-size:14px; padding:6px;">'+esc(t.hostname||"-")+"</td>",
e+='<td style="color:#90CAF9; font-size:14px; padding:6px;">'+esc(t.ip||"-")+"</td>",e+='<td style="color:#ccc; font-size:14px; padding:6px; font-family:monospace;">'+esc(t.mac)+"</td>",
e+='<td style="color:'+r+'; font-size:14px; padding:6px; font-weight:600;">'+(Number(t.signal)||"?")+" dBm</td>",e+="</tr>"})),e+="</table></div></div>"}})),t.some((function(t){
var e=Array.isArray(t.clients)?t.clients:t.clients&&"object"==typeof t.clients?Object.values(t.clients):[];return e&&e.length>0}))||(e+='<div style="padding:20px;text-align:center;color:#999;">No connected clients</div>'),
document.getElementById("wireless-widget").innerHTML=e):document.getElementById("wireless-widget").innerHTML='<div style="padding:20px;text-align:center;color:#999;">No wireless radios found</div>'}function renderTempWidget(t){
var e,r=t.cpu_temp;if(null==r)e='<div style="padding:20px;text-align:center;color:#999;">Sensor unavailable</div>';else{var a=r<70?"#4CAF50":r<90?"#FF9800":"#F44336"
;e='<div style="line-height:1.2; text-align:center;"><div style="font-size:30px; margin-bottom:6px;">🌡️</div><div style="font-size:16px; color:#aaa; text-transform:uppercase; letter-spacing:0.5px;">CPU Temp</div><div style="font-size:34px; font-weight:700; color:'+a+'; margin-top:6px;">'+r+'°C</div><div style="font-size:14px; color:'+a+'; margin-top:4px;">'+(r<70?"Normal":r<90?"Hot":"Critical")+"</div></div>"
}document.getElementById("temp-widget").innerHTML=e}function loadDashboardData(){fetch("/cgi-bin/luci/admin/dashboard/api?cpu_prev="+cpuPrev).then((function(t){return t.json()})).then((function(t){t.cpu&&t.cpu.prev&&(cpuPrev=t.cpu.prev),
t.network&&Array.isArray(t.network)&&t.port_stats&&(t.network=mergeTrafficData(t.network,t.port_stats)),renderNetworkWidget(t.network||[]),renderWirelessWidget(t.wireless||[]),renderTempWidget(t.temperature||{cpu_temp:null}),
t.cpu&&renderCPUWidget(t.cpu),t.memory&&renderMemoryWidget(t.memory),t.storage&&renderStorageWidget(t.storage)})).catch((function(t){console.error("Error loading dashboard data:",t)}))}function formatBytes(t){if(!t||0===t)return"0 B"
;var e=Math.floor(Math.log(t)/Math.log(1024));return parseFloat((t/Math.pow(1024,e)).toFixed(1))+" "+["B","KB","MB","GB","TB"][e]}cpuPrev="0,0",window.addEventListener("load",(function(){setTimeout((function(){loadSystemInfo(),
loadDashboardData(),setInterval(loadDashboardData,2e3)}),1e3)}));